// Code generated by entc, DO NOT EDIT.

package usermeta

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the usermeta type in the database.
	Label = "user_meta"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmailNotification holds the string denoting the email_notification field in the database.
	FieldEmailNotification = "email_notification"
	// FieldEmailPromotions holds the string denoting the email_promotions field in the database.
	FieldEmailPromotions = "email_promotions"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the usermeta in the database.
	Table = "user_meta"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "user_meta"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "fk_user_id"
)

// Columns holds all SQL columns for usermeta fields.
var Columns = []string{
	FieldID,
	FieldEmailNotification,
	FieldEmailPromotions,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the UserMeta type.
var ForeignKeys = []string{
	"fk_user_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEmailNotification holds the default value on creation for the "email_notification" field.
	DefaultEmailNotification bool
	// DefaultEmailPromotions holds the default value on creation for the "email_promotions" field.
	DefaultEmailPromotions bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
