// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/OhMinsSup/story-server/ent/predicate"
	"github.com/OhMinsSup/story-server/ent/socialaccount"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/google/uuid"
)

// SocialAccountQuery is the builder for querying SocialAccount entities.
type SocialAccountQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.SocialAccount
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SocialAccountQuery builder.
func (saq *SocialAccountQuery) Where(ps ...predicate.SocialAccount) *SocialAccountQuery {
	saq.predicates = append(saq.predicates, ps...)
	return saq
}

// Limit adds a limit step to the query.
func (saq *SocialAccountQuery) Limit(limit int) *SocialAccountQuery {
	saq.limit = &limit
	return saq
}

// Offset adds an offset step to the query.
func (saq *SocialAccountQuery) Offset(offset int) *SocialAccountQuery {
	saq.offset = &offset
	return saq
}

// Order adds an order step to the query.
func (saq *SocialAccountQuery) Order(o ...OrderFunc) *SocialAccountQuery {
	saq.order = append(saq.order, o...)
	return saq
}

// First returns the first SocialAccount entity from the query.
// Returns a *NotFoundError when no SocialAccount was found.
func (saq *SocialAccountQuery) First(ctx context.Context) (*SocialAccount, error) {
	nodes, err := saq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{socialaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (saq *SocialAccountQuery) FirstX(ctx context.Context) *SocialAccount {
	node, err := saq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SocialAccount ID from the query.
// Returns a *NotFoundError when no SocialAccount ID was found.
func (saq *SocialAccountQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = saq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{socialaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (saq *SocialAccountQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := saq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SocialAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one SocialAccount entity is not found.
// Returns a *NotFoundError when no SocialAccount entities are found.
func (saq *SocialAccountQuery) Only(ctx context.Context) (*SocialAccount, error) {
	nodes, err := saq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{socialaccount.Label}
	default:
		return nil, &NotSingularError{socialaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (saq *SocialAccountQuery) OnlyX(ctx context.Context) *SocialAccount {
	node, err := saq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SocialAccount ID in the query.
// Returns a *NotSingularError when exactly one SocialAccount ID is not found.
// Returns a *NotFoundError when no entities are found.
func (saq *SocialAccountQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = saq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{socialaccount.Label}
	default:
		err = &NotSingularError{socialaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (saq *SocialAccountQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := saq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SocialAccounts.
func (saq *SocialAccountQuery) All(ctx context.Context) ([]*SocialAccount, error) {
	if err := saq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return saq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (saq *SocialAccountQuery) AllX(ctx context.Context) []*SocialAccount {
	nodes, err := saq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SocialAccount IDs.
func (saq *SocialAccountQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := saq.Select(socialaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (saq *SocialAccountQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := saq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (saq *SocialAccountQuery) Count(ctx context.Context) (int, error) {
	if err := saq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return saq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (saq *SocialAccountQuery) CountX(ctx context.Context) int {
	count, err := saq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (saq *SocialAccountQuery) Exist(ctx context.Context) (bool, error) {
	if err := saq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return saq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (saq *SocialAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := saq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SocialAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (saq *SocialAccountQuery) Clone() *SocialAccountQuery {
	if saq == nil {
		return nil
	}
	return &SocialAccountQuery{
		config:     saq.config,
		limit:      saq.limit,
		offset:     saq.offset,
		order:      append([]OrderFunc{}, saq.order...),
		predicates: append([]predicate.SocialAccount{}, saq.predicates...),
		// clone intermediate query.
		sql:  saq.sql.Clone(),
		path: saq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SocialID string `json:"social_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SocialAccount.Query().
//		GroupBy(socialaccount.FieldSocialID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (saq *SocialAccountQuery) GroupBy(field string, fields ...string) *SocialAccountGroupBy {
	group := &SocialAccountGroupBy{config: saq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := saq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return saq.sqlQuery(), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SocialID string `json:"social_id,omitempty"`
//	}
//
//	client.SocialAccount.Query().
//		Select(socialaccount.FieldSocialID).
//		Scan(ctx, &v)
//
func (saq *SocialAccountQuery) Select(field string, fields ...string) *SocialAccountSelect {
	saq.fields = append([]string{field}, fields...)
	return &SocialAccountSelect{SocialAccountQuery: saq}
}

func (saq *SocialAccountQuery) prepareQuery(ctx context.Context) error {
	for _, f := range saq.fields {
		if !socialaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if saq.path != nil {
		prev, err := saq.path(ctx)
		if err != nil {
			return err
		}
		saq.sql = prev
	}
	return nil
}

func (saq *SocialAccountQuery) sqlAll(ctx context.Context) ([]*SocialAccount, error) {
	var (
		nodes = []*SocialAccount{}
		_spec = saq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &SocialAccount{config: saq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, saq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (saq *SocialAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := saq.querySpec()
	return sqlgraph.CountNodes(ctx, saq.driver, _spec)
}

func (saq *SocialAccountQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := saq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (saq *SocialAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   socialaccount.Table,
			Columns: socialaccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: socialaccount.FieldID,
			},
		},
		From:   saq.sql,
		Unique: true,
	}
	if fields := saq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, socialaccount.FieldID)
		for i := range fields {
			if fields[i] != socialaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := saq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := saq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := saq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := saq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, socialaccount.ValidColumn)
			}
		}
	}
	return _spec
}

func (saq *SocialAccountQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(saq.driver.Dialect())
	t1 := builder.Table(socialaccount.Table)
	selector := builder.Select(t1.Columns(socialaccount.Columns...)...).From(t1)
	if saq.sql != nil {
		selector = saq.sql
		selector.Select(selector.Columns(socialaccount.Columns...)...)
	}
	for _, p := range saq.predicates {
		p(selector)
	}
	for _, p := range saq.order {
		p(selector, socialaccount.ValidColumn)
	}
	if offset := saq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := saq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SocialAccountGroupBy is the group-by builder for SocialAccount entities.
type SocialAccountGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sagb *SocialAccountGroupBy) Aggregate(fns ...AggregateFunc) *SocialAccountGroupBy {
	sagb.fns = append(sagb.fns, fns...)
	return sagb
}

// Scan applies the group-by query and scans the result into the given value.
func (sagb *SocialAccountGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sagb.path(ctx)
	if err != nil {
		return err
	}
	sagb.sql = query
	return sagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sagb *SocialAccountGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := sagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (sagb *SocialAccountGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(sagb.fields) > 1 {
		return nil, errors.New("ent: SocialAccountGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := sagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sagb *SocialAccountGroupBy) StringsX(ctx context.Context) []string {
	v, err := sagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sagb *SocialAccountGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{socialaccount.Label}
	default:
		err = fmt.Errorf("ent: SocialAccountGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sagb *SocialAccountGroupBy) StringX(ctx context.Context) string {
	v, err := sagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (sagb *SocialAccountGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(sagb.fields) > 1 {
		return nil, errors.New("ent: SocialAccountGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := sagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sagb *SocialAccountGroupBy) IntsX(ctx context.Context) []int {
	v, err := sagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sagb *SocialAccountGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{socialaccount.Label}
	default:
		err = fmt.Errorf("ent: SocialAccountGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sagb *SocialAccountGroupBy) IntX(ctx context.Context) int {
	v, err := sagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (sagb *SocialAccountGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(sagb.fields) > 1 {
		return nil, errors.New("ent: SocialAccountGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := sagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sagb *SocialAccountGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := sagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sagb *SocialAccountGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{socialaccount.Label}
	default:
		err = fmt.Errorf("ent: SocialAccountGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sagb *SocialAccountGroupBy) Float64X(ctx context.Context) float64 {
	v, err := sagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (sagb *SocialAccountGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(sagb.fields) > 1 {
		return nil, errors.New("ent: SocialAccountGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := sagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sagb *SocialAccountGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := sagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sagb *SocialAccountGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{socialaccount.Label}
	default:
		err = fmt.Errorf("ent: SocialAccountGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sagb *SocialAccountGroupBy) BoolX(ctx context.Context) bool {
	v, err := sagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sagb *SocialAccountGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sagb.fields {
		if !socialaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sagb *SocialAccountGroupBy) sqlQuery() *sql.Selector {
	selector := sagb.sql
	columns := make([]string, 0, len(sagb.fields)+len(sagb.fns))
	columns = append(columns, sagb.fields...)
	for _, fn := range sagb.fns {
		columns = append(columns, fn(selector, socialaccount.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(sagb.fields...)
}

// SocialAccountSelect is the builder for selecting fields of SocialAccount entities.
type SocialAccountSelect struct {
	*SocialAccountQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sas *SocialAccountSelect) Scan(ctx context.Context, v interface{}) error {
	if err := sas.prepareQuery(ctx); err != nil {
		return err
	}
	sas.sql = sas.SocialAccountQuery.sqlQuery()
	return sas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sas *SocialAccountSelect) ScanX(ctx context.Context, v interface{}) {
	if err := sas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (sas *SocialAccountSelect) Strings(ctx context.Context) ([]string, error) {
	if len(sas.fields) > 1 {
		return nil, errors.New("ent: SocialAccountSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := sas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sas *SocialAccountSelect) StringsX(ctx context.Context) []string {
	v, err := sas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (sas *SocialAccountSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{socialaccount.Label}
	default:
		err = fmt.Errorf("ent: SocialAccountSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sas *SocialAccountSelect) StringX(ctx context.Context) string {
	v, err := sas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (sas *SocialAccountSelect) Ints(ctx context.Context) ([]int, error) {
	if len(sas.fields) > 1 {
		return nil, errors.New("ent: SocialAccountSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := sas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sas *SocialAccountSelect) IntsX(ctx context.Context) []int {
	v, err := sas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (sas *SocialAccountSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{socialaccount.Label}
	default:
		err = fmt.Errorf("ent: SocialAccountSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sas *SocialAccountSelect) IntX(ctx context.Context) int {
	v, err := sas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (sas *SocialAccountSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(sas.fields) > 1 {
		return nil, errors.New("ent: SocialAccountSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := sas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sas *SocialAccountSelect) Float64sX(ctx context.Context) []float64 {
	v, err := sas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (sas *SocialAccountSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{socialaccount.Label}
	default:
		err = fmt.Errorf("ent: SocialAccountSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sas *SocialAccountSelect) Float64X(ctx context.Context) float64 {
	v, err := sas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (sas *SocialAccountSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(sas.fields) > 1 {
		return nil, errors.New("ent: SocialAccountSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := sas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sas *SocialAccountSelect) BoolsX(ctx context.Context) []bool {
	v, err := sas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (sas *SocialAccountSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{socialaccount.Label}
	default:
		err = fmt.Errorf("ent: SocialAccountSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sas *SocialAccountSelect) BoolX(ctx context.Context) bool {
	v, err := sas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sas *SocialAccountSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sas.sqlQuery().Query()
	if err := sas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sas *SocialAccountSelect) sqlQuery() sql.Querier {
	selector := sas.sql
	selector.Select(selector.Columns(sas.fields...)...)
	return selector
}
