// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/OhMinsSup/story-server/ent/user"
	"github.com/OhMinsSup/story-server/ent/usermeta"
	"github.com/facebook/ent/dialect/sql"
	"github.com/google/uuid"
)

// UserMeta is the model entity for the UserMeta schema.
type UserMeta struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// EmailNotification holds the value of the "email_notification" field.
	EmailNotification bool `json:"email_notification,omitempty"`
	// EmailPromotions holds the value of the "email_promotions" field.
	EmailPromotions bool `json:"email_promotions,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserMetaQuery when eager-loading is set.
	Edges      UserMetaEdges `json:"edges"`
	fk_user_id *uuid.UUID
}

// UserMetaEdges holds the relations/edges for other nodes in the graph.
type UserMetaEdges struct {
	// User holds the value of the user edge.
	User *User
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserMetaEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserMeta) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case usermeta.FieldEmailNotification, usermeta.FieldEmailPromotions:
			values[i] = &sql.NullBool{}
		case usermeta.FieldCreatedAt, usermeta.FieldUpdatedAt:
			values[i] = &sql.NullTime{}
		case usermeta.FieldID:
			values[i] = &uuid.UUID{}
		case usermeta.ForeignKeys[0]: // fk_user_id
			values[i] = &uuid.UUID{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type UserMeta", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserMeta fields.
func (um *UserMeta) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usermeta.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				um.ID = *value
			}
		case usermeta.FieldEmailNotification:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field email_notification", values[i])
			} else if value.Valid {
				um.EmailNotification = value.Bool
			}
		case usermeta.FieldEmailPromotions:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field email_promotions", values[i])
			} else if value.Valid {
				um.EmailPromotions = value.Bool
			}
		case usermeta.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				um.CreatedAt = value.Time
			}
		case usermeta.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				um.UpdatedAt = value.Time
			}
		case usermeta.ForeignKeys[0]:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field fk_user_id", values[i])
			} else if value != nil {
				um.fk_user_id = value
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the UserMeta entity.
func (um *UserMeta) QueryUser() *UserQuery {
	return (&UserMetaClient{config: um.config}).QueryUser(um)
}

// Update returns a builder for updating this UserMeta.
// Note that you need to call UserMeta.Unwrap() before calling this method if this UserMeta
// was returned from a transaction, and the transaction was committed or rolled back.
func (um *UserMeta) Update() *UserMetaUpdateOne {
	return (&UserMetaClient{config: um.config}).UpdateOne(um)
}

// Unwrap unwraps the UserMeta entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (um *UserMeta) Unwrap() *UserMeta {
	tx, ok := um.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserMeta is not a transactional entity")
	}
	um.config.driver = tx.drv
	return um
}

// String implements the fmt.Stringer.
func (um *UserMeta) String() string {
	var builder strings.Builder
	builder.WriteString("UserMeta(")
	builder.WriteString(fmt.Sprintf("id=%v", um.ID))
	builder.WriteString(", email_notification=")
	builder.WriteString(fmt.Sprintf("%v", um.EmailNotification))
	builder.WriteString(", email_promotions=")
	builder.WriteString(fmt.Sprintf("%v", um.EmailPromotions))
	builder.WriteString(", created_at=")
	builder.WriteString(um.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(um.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserMetaSlice is a parsable slice of UserMeta.
type UserMetaSlice []*UserMeta

func (um UserMetaSlice) config(cfg config) {
	for _i := range um {
		um[_i].config = cfg
	}
}
