// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/OhMinsSup/story-server/ent/predicate"
	"github.com/OhMinsSup/story-server/ent/user"
	"github.com/OhMinsSup/story-server/ent/usermeta"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/google/uuid"
)

// UserMetaUpdate is the builder for updating UserMeta entities.
type UserMetaUpdate struct {
	config
	hooks    []Hook
	mutation *UserMetaMutation
}

// Where adds a new predicate for the UserMetaUpdate builder.
func (umu *UserMetaUpdate) Where(ps ...predicate.UserMeta) *UserMetaUpdate {
	umu.mutation.predicates = append(umu.mutation.predicates, ps...)
	return umu
}

// SetEmailNotification sets the "email_notification" field.
func (umu *UserMetaUpdate) SetEmailNotification(b bool) *UserMetaUpdate {
	umu.mutation.SetEmailNotification(b)
	return umu
}

// SetNillableEmailNotification sets the "email_notification" field if the given value is not nil.
func (umu *UserMetaUpdate) SetNillableEmailNotification(b *bool) *UserMetaUpdate {
	if b != nil {
		umu.SetEmailNotification(*b)
	}
	return umu
}

// SetEmailPromotions sets the "email_promotions" field.
func (umu *UserMetaUpdate) SetEmailPromotions(b bool) *UserMetaUpdate {
	umu.mutation.SetEmailPromotions(b)
	return umu
}

// SetNillableEmailPromotions sets the "email_promotions" field if the given value is not nil.
func (umu *UserMetaUpdate) SetNillableEmailPromotions(b *bool) *UserMetaUpdate {
	if b != nil {
		umu.SetEmailPromotions(*b)
	}
	return umu
}

// SetUpdatedAt sets the "updated_at" field.
func (umu *UserMetaUpdate) SetUpdatedAt(t time.Time) *UserMetaUpdate {
	umu.mutation.SetUpdatedAt(t)
	return umu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (umu *UserMetaUpdate) SetUserID(id uuid.UUID) *UserMetaUpdate {
	umu.mutation.SetUserID(id)
	return umu
}

// SetUser sets the "user" edge to the User entity.
func (umu *UserMetaUpdate) SetUser(u *User) *UserMetaUpdate {
	return umu.SetUserID(u.ID)
}

// Mutation returns the UserMetaMutation object of the builder.
func (umu *UserMetaUpdate) Mutation() *UserMetaMutation {
	return umu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (umu *UserMetaUpdate) ClearUser() *UserMetaUpdate {
	umu.mutation.ClearUser()
	return umu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (umu *UserMetaUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	umu.defaults()
	if len(umu.hooks) == 0 {
		if err = umu.check(); err != nil {
			return 0, err
		}
		affected, err = umu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMetaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = umu.check(); err != nil {
				return 0, err
			}
			umu.mutation = mutation
			affected, err = umu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(umu.hooks) - 1; i >= 0; i-- {
			mut = umu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, umu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (umu *UserMetaUpdate) SaveX(ctx context.Context) int {
	affected, err := umu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (umu *UserMetaUpdate) Exec(ctx context.Context) error {
	_, err := umu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umu *UserMetaUpdate) ExecX(ctx context.Context) {
	if err := umu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (umu *UserMetaUpdate) defaults() {
	if _, ok := umu.mutation.UpdatedAt(); !ok {
		v := usermeta.UpdateDefaultUpdatedAt()
		umu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (umu *UserMetaUpdate) check() error {
	if _, ok := umu.mutation.UserID(); umu.mutation.UserCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"user\"")
	}
	return nil
}

func (umu *UserMetaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usermeta.Table,
			Columns: usermeta.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: usermeta.FieldID,
			},
		},
	}
	if ps := umu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := umu.mutation.EmailNotification(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: usermeta.FieldEmailNotification,
		})
	}
	if value, ok := umu.mutation.EmailPromotions(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: usermeta.FieldEmailPromotions,
		})
	}
	if value, ok := umu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: usermeta.FieldUpdatedAt,
		})
	}
	if umu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usermeta.UserTable,
			Columns: []string{usermeta.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := umu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usermeta.UserTable,
			Columns: []string{usermeta.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, umu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermeta.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// UserMetaUpdateOne is the builder for updating a single UserMeta entity.
type UserMetaUpdateOne struct {
	config
	hooks    []Hook
	mutation *UserMetaMutation
}

// SetEmailNotification sets the "email_notification" field.
func (umuo *UserMetaUpdateOne) SetEmailNotification(b bool) *UserMetaUpdateOne {
	umuo.mutation.SetEmailNotification(b)
	return umuo
}

// SetNillableEmailNotification sets the "email_notification" field if the given value is not nil.
func (umuo *UserMetaUpdateOne) SetNillableEmailNotification(b *bool) *UserMetaUpdateOne {
	if b != nil {
		umuo.SetEmailNotification(*b)
	}
	return umuo
}

// SetEmailPromotions sets the "email_promotions" field.
func (umuo *UserMetaUpdateOne) SetEmailPromotions(b bool) *UserMetaUpdateOne {
	umuo.mutation.SetEmailPromotions(b)
	return umuo
}

// SetNillableEmailPromotions sets the "email_promotions" field if the given value is not nil.
func (umuo *UserMetaUpdateOne) SetNillableEmailPromotions(b *bool) *UserMetaUpdateOne {
	if b != nil {
		umuo.SetEmailPromotions(*b)
	}
	return umuo
}

// SetUpdatedAt sets the "updated_at" field.
func (umuo *UserMetaUpdateOne) SetUpdatedAt(t time.Time) *UserMetaUpdateOne {
	umuo.mutation.SetUpdatedAt(t)
	return umuo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (umuo *UserMetaUpdateOne) SetUserID(id uuid.UUID) *UserMetaUpdateOne {
	umuo.mutation.SetUserID(id)
	return umuo
}

// SetUser sets the "user" edge to the User entity.
func (umuo *UserMetaUpdateOne) SetUser(u *User) *UserMetaUpdateOne {
	return umuo.SetUserID(u.ID)
}

// Mutation returns the UserMetaMutation object of the builder.
func (umuo *UserMetaUpdateOne) Mutation() *UserMetaMutation {
	return umuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (umuo *UserMetaUpdateOne) ClearUser() *UserMetaUpdateOne {
	umuo.mutation.ClearUser()
	return umuo
}

// Save executes the query and returns the updated UserMeta entity.
func (umuo *UserMetaUpdateOne) Save(ctx context.Context) (*UserMeta, error) {
	var (
		err  error
		node *UserMeta
	)
	umuo.defaults()
	if len(umuo.hooks) == 0 {
		if err = umuo.check(); err != nil {
			return nil, err
		}
		node, err = umuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMetaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = umuo.check(); err != nil {
				return nil, err
			}
			umuo.mutation = mutation
			node, err = umuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(umuo.hooks) - 1; i >= 0; i-- {
			mut = umuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, umuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (umuo *UserMetaUpdateOne) SaveX(ctx context.Context) *UserMeta {
	node, err := umuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (umuo *UserMetaUpdateOne) Exec(ctx context.Context) error {
	_, err := umuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umuo *UserMetaUpdateOne) ExecX(ctx context.Context) {
	if err := umuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (umuo *UserMetaUpdateOne) defaults() {
	if _, ok := umuo.mutation.UpdatedAt(); !ok {
		v := usermeta.UpdateDefaultUpdatedAt()
		umuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (umuo *UserMetaUpdateOne) check() error {
	if _, ok := umuo.mutation.UserID(); umuo.mutation.UserCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"user\"")
	}
	return nil
}

func (umuo *UserMetaUpdateOne) sqlSave(ctx context.Context) (_node *UserMeta, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usermeta.Table,
			Columns: usermeta.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: usermeta.FieldID,
			},
		},
	}
	id, ok := umuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing UserMeta.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := umuo.mutation.EmailNotification(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: usermeta.FieldEmailNotification,
		})
	}
	if value, ok := umuo.mutation.EmailPromotions(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: usermeta.FieldEmailPromotions,
		})
	}
	if value, ok := umuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: usermeta.FieldUpdatedAt,
		})
	}
	if umuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usermeta.UserTable,
			Columns: []string{usermeta.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := umuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usermeta.UserTable,
			Columns: []string{usermeta.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserMeta{config: umuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, umuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermeta.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
