// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/OhMinsSup/story-server/ent/user"
	"github.com/OhMinsSup/story-server/ent/velogconfig"
	"github.com/facebook/ent/dialect/sql"
	"github.com/google/uuid"
)

// VelogConfig is the model entity for the VelogConfig schema.
type VelogConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title *string `json:"title,omitempty"`
	// LogoTitle holds the value of the "logo_title" field.
	LogoTitle *string `json:"logo_title,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VelogConfigQuery when eager-loading is set.
	Edges      VelogConfigEdges `json:"edges"`
	fk_user_id *uuid.UUID
}

// VelogConfigEdges holds the relations/edges for other nodes in the graph.
type VelogConfigEdges struct {
	// User holds the value of the user edge.
	User *User
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VelogConfigEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VelogConfig) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case velogconfig.FieldTitle, velogconfig.FieldLogoTitle:
			values[i] = &sql.NullString{}
		case velogconfig.FieldCreatedAt, velogconfig.FieldUpdatedAt:
			values[i] = &sql.NullTime{}
		case velogconfig.FieldID:
			values[i] = &uuid.UUID{}
		case velogconfig.ForeignKeys[0]: // fk_user_id
			values[i] = &uuid.UUID{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type VelogConfig", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VelogConfig fields.
func (vc *VelogConfig) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case velogconfig.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				vc.ID = *value
			}
		case velogconfig.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				vc.Title = new(string)
				*vc.Title = value.String
			}
		case velogconfig.FieldLogoTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo_title", values[i])
			} else if value.Valid {
				vc.LogoTitle = new(string)
				*vc.LogoTitle = value.String
			}
		case velogconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				vc.CreatedAt = value.Time
			}
		case velogconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				vc.UpdatedAt = value.Time
			}
		case velogconfig.ForeignKeys[0]:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field fk_user_id", values[i])
			} else if value != nil {
				vc.fk_user_id = value
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the VelogConfig entity.
func (vc *VelogConfig) QueryUser() *UserQuery {
	return (&VelogConfigClient{config: vc.config}).QueryUser(vc)
}

// Update returns a builder for updating this VelogConfig.
// Note that you need to call VelogConfig.Unwrap() before calling this method if this VelogConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (vc *VelogConfig) Update() *VelogConfigUpdateOne {
	return (&VelogConfigClient{config: vc.config}).UpdateOne(vc)
}

// Unwrap unwraps the VelogConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (vc *VelogConfig) Unwrap() *VelogConfig {
	tx, ok := vc.config.driver.(*txDriver)
	if !ok {
		panic("ent: VelogConfig is not a transactional entity")
	}
	vc.config.driver = tx.drv
	return vc
}

// String implements the fmt.Stringer.
func (vc *VelogConfig) String() string {
	var builder strings.Builder
	builder.WriteString("VelogConfig(")
	builder.WriteString(fmt.Sprintf("id=%v", vc.ID))
	if v := vc.Title; v != nil {
		builder.WriteString(", title=")
		builder.WriteString(*v)
	}
	if v := vc.LogoTitle; v != nil {
		builder.WriteString(", logo_title=")
		builder.WriteString(*v)
	}
	builder.WriteString(", created_at=")
	builder.WriteString(vc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(vc.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VelogConfigs is a parsable slice of VelogConfig.
type VelogConfigs []*VelogConfig

func (vc VelogConfigs) config(cfg config) {
	for _i := range vc {
		vc[_i].config = cfg
	}
}
