// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/OhMinsSup/story-server/ent/user"
	"github.com/OhMinsSup/story-server/ent/velogconfig"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/google/uuid"
)

// VelogConfigCreate is the builder for creating a VelogConfig entity.
type VelogConfigCreate struct {
	config
	mutation *VelogConfigMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (vcc *VelogConfigCreate) SetTitle(s string) *VelogConfigCreate {
	vcc.mutation.SetTitle(s)
	return vcc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (vcc *VelogConfigCreate) SetNillableTitle(s *string) *VelogConfigCreate {
	if s != nil {
		vcc.SetTitle(*s)
	}
	return vcc
}

// SetLogoTitle sets the "logo_title" field.
func (vcc *VelogConfigCreate) SetLogoTitle(s string) *VelogConfigCreate {
	vcc.mutation.SetLogoTitle(s)
	return vcc
}

// SetNillableLogoTitle sets the "logo_title" field if the given value is not nil.
func (vcc *VelogConfigCreate) SetNillableLogoTitle(s *string) *VelogConfigCreate {
	if s != nil {
		vcc.SetLogoTitle(*s)
	}
	return vcc
}

// SetCreatedAt sets the "created_at" field.
func (vcc *VelogConfigCreate) SetCreatedAt(t time.Time) *VelogConfigCreate {
	vcc.mutation.SetCreatedAt(t)
	return vcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (vcc *VelogConfigCreate) SetNillableCreatedAt(t *time.Time) *VelogConfigCreate {
	if t != nil {
		vcc.SetCreatedAt(*t)
	}
	return vcc
}

// SetUpdatedAt sets the "updated_at" field.
func (vcc *VelogConfigCreate) SetUpdatedAt(t time.Time) *VelogConfigCreate {
	vcc.mutation.SetUpdatedAt(t)
	return vcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (vcc *VelogConfigCreate) SetNillableUpdatedAt(t *time.Time) *VelogConfigCreate {
	if t != nil {
		vcc.SetUpdatedAt(*t)
	}
	return vcc
}

// SetID sets the "id" field.
func (vcc *VelogConfigCreate) SetID(u uuid.UUID) *VelogConfigCreate {
	vcc.mutation.SetID(u)
	return vcc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (vcc *VelogConfigCreate) SetUserID(id uuid.UUID) *VelogConfigCreate {
	vcc.mutation.SetUserID(id)
	return vcc
}

// SetUser sets the "user" edge to the User entity.
func (vcc *VelogConfigCreate) SetUser(u *User) *VelogConfigCreate {
	return vcc.SetUserID(u.ID)
}

// Mutation returns the VelogConfigMutation object of the builder.
func (vcc *VelogConfigCreate) Mutation() *VelogConfigMutation {
	return vcc.mutation
}

// Save creates the VelogConfig in the database.
func (vcc *VelogConfigCreate) Save(ctx context.Context) (*VelogConfig, error) {
	var (
		err  error
		node *VelogConfig
	)
	vcc.defaults()
	if len(vcc.hooks) == 0 {
		if err = vcc.check(); err != nil {
			return nil, err
		}
		node, err = vcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VelogConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = vcc.check(); err != nil {
				return nil, err
			}
			vcc.mutation = mutation
			node, err = vcc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(vcc.hooks) - 1; i >= 0; i-- {
			mut = vcc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vcc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (vcc *VelogConfigCreate) SaveX(ctx context.Context) *VelogConfig {
	v, err := vcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (vcc *VelogConfigCreate) defaults() {
	if _, ok := vcc.mutation.CreatedAt(); !ok {
		v := velogconfig.DefaultCreatedAt()
		vcc.mutation.SetCreatedAt(v)
	}
	if _, ok := vcc.mutation.UpdatedAt(); !ok {
		v := velogconfig.DefaultUpdatedAt()
		vcc.mutation.SetUpdatedAt(v)
	}
	if _, ok := vcc.mutation.ID(); !ok {
		v := velogconfig.DefaultID()
		vcc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vcc *VelogConfigCreate) check() error {
	if _, ok := vcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New("ent: missing required field \"created_at\"")}
	}
	if _, ok := vcc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New("ent: missing required field \"updated_at\"")}
	}
	if _, ok := vcc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New("ent: missing required edge \"user\"")}
	}
	return nil
}

func (vcc *VelogConfigCreate) sqlSave(ctx context.Context) (*VelogConfig, error) {
	_node, _spec := vcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vcc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}

func (vcc *VelogConfigCreate) createSpec() (*VelogConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &VelogConfig{config: vcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: velogconfig.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: velogconfig.FieldID,
			},
		}
	)
	if id, ok := vcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := vcc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: velogconfig.FieldTitle,
		})
		_node.Title = &value
	}
	if value, ok := vcc.mutation.LogoTitle(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: velogconfig.FieldLogoTitle,
		})
		_node.LogoTitle = &value
	}
	if value, ok := vcc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: velogconfig.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := vcc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: velogconfig.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := vcc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   velogconfig.UserTable,
			Columns: []string{velogconfig.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VelogConfigCreateBulk is the builder for creating many VelogConfig entities in bulk.
type VelogConfigCreateBulk struct {
	config
	builders []*VelogConfigCreate
}

// Save creates the VelogConfig entities in the database.
func (vccb *VelogConfigCreateBulk) Save(ctx context.Context) ([]*VelogConfig, error) {
	specs := make([]*sqlgraph.CreateSpec, len(vccb.builders))
	nodes := make([]*VelogConfig, len(vccb.builders))
	mutators := make([]Mutator, len(vccb.builders))
	for i := range vccb.builders {
		func(i int, root context.Context) {
			builder := vccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VelogConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vccb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vccb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vccb *VelogConfigCreateBulk) SaveX(ctx context.Context) []*VelogConfig {
	v, err := vccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
