// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/OhMinsSup/story-server/ent/predicate"
	"github.com/OhMinsSup/story-server/ent/velogconfig"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// VelogConfigDelete is the builder for deleting a VelogConfig entity.
type VelogConfigDelete struct {
	config
	hooks    []Hook
	mutation *VelogConfigMutation
}

// Where adds a new predicate to the VelogConfigDelete builder.
func (vcd *VelogConfigDelete) Where(ps ...predicate.VelogConfig) *VelogConfigDelete {
	vcd.mutation.predicates = append(vcd.mutation.predicates, ps...)
	return vcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vcd *VelogConfigDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vcd.hooks) == 0 {
		affected, err = vcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VelogConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vcd.mutation = mutation
			affected, err = vcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vcd.hooks) - 1; i >= 0; i-- {
			mut = vcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (vcd *VelogConfigDelete) ExecX(ctx context.Context) int {
	n, err := vcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vcd *VelogConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: velogconfig.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: velogconfig.FieldID,
			},
		},
	}
	if ps := vcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, vcd.driver, _spec)
}

// VelogConfigDeleteOne is the builder for deleting a single VelogConfig entity.
type VelogConfigDeleteOne struct {
	vcd *VelogConfigDelete
}

// Exec executes the deletion query.
func (vcdo *VelogConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := vcdo.vcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{velogconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vcdo *VelogConfigDeleteOne) ExecX(ctx context.Context) {
	vcdo.vcd.ExecX(ctx)
}
