// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// AuthToken is the predicate function for authtoken builders.
type AuthToken func(*sql.Selector)

// EmailAuth is the predicate function for emailauth builders.
type EmailAuth func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// SocialAccount is the predicate function for socialaccount builders.
type SocialAccount func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserMeta is the predicate function for usermeta builders.
type UserMeta func(*sql.Selector)

// UserProfile is the predicate function for userprofile builders.
type UserProfile func(*sql.Selector)

// VelogConfig is the predicate function for velogconfig builders.
type VelogConfig func(*sql.Selector)
