// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// EmailAuth is the predicate function for emailauth builders.
type EmailAuth func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserProfile is the predicate function for userprofile builders.
type UserProfile func(*sql.Selector)
